// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3iTIRci4npozb6294uTgjQcxmeYPEULk',
    appId: '1:873632745898:web:2d836f2196393fec2983d3',
    messagingSenderId: '873632745898',
    projectId: 'healthsync-cea1a',
    authDomain: 'healthsync-cea1a.firebaseapp.com',
    storageBucket: 'healthsync-cea1a.firebasestorage.app',
    measurementId: 'G-NNFQFC4CWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNJSRlLaLnZ0REzHWmaEVySjQ8o2k30a8',
    appId: '1:873632745898:android:7b6ce3f6728192702983d3',
    messagingSenderId: '873632745898',
    projectId: 'healthsync-cea1a',
    storageBucket: 'healthsync-cea1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM_-ARyWN7W3asPYFqvBVVF94L-MZuZmU',
    appId: '1:873632745898:ios:2f5ec084d436149d2983d3',
    messagingSenderId: '873632745898',
    projectId: 'healthsync-cea1a',
    storageBucket: 'healthsync-cea1a.firebasestorage.app',
    iosBundleId: 'com.pao.healthsyncApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM_-ARyWN7W3asPYFqvBVVF94L-MZuZmU',
    appId: '1:873632745898:ios:2f5ec084d436149d2983d3',
    messagingSenderId: '873632745898',
    projectId: 'healthsync-cea1a',
    storageBucket: 'healthsync-cea1a.firebasestorage.app',
    iosBundleId: 'com.pao.healthsyncApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3iTIRci4npozb6294uTgjQcxmeYPEULk',
    appId: '1:873632745898:web:4f7f07701f55afd72983d3',
    messagingSenderId: '873632745898',
    projectId: 'healthsync-cea1a',
    authDomain: 'healthsync-cea1a.firebaseapp.com',
    storageBucket: 'healthsync-cea1a.firebasestorage.app',
    measurementId: 'G-CJS5EVETW0',
  );
}
